apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: kafka
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: kafka-brokers
        static_configs:
          - targets:
              - kafka-kafka-0.kafka-kafka-brokers.kafka.svc:9404
              - kafka-kafka-1.kafka-kafka-brokers.kafka.svc:9404
              - kafka-kafka-2.kafka-kafka-brokers.kafka.svc:9404
        metrics_path: /metrics
