apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: kafka
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  replicas: 3
  roles:
    - controller
    - broker
  resources:
    requests:
      cpu: "4"
      memory: 4Gi
    limits:
      cpu: "4"
      memory: 6Gi
  template:
    pod:
      metadata:
        annotations:
          kafka.strimzi.io/log-sidecar: "enabled"
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
      templatedVolumes:
        - name: broker-runtime-logs
          persistentVolumeClaim:
            claimName: kafka-runtime-logs-{nodeId}
    kafkaContainer:
      env:
        - name: KAFKA_HEALTH_STATUS_TTL_SECONDS
          value: "30"
      volumeMounts:
        - name: broker-runtime-logs
          mountPath: /mnt/kafka-runtime-logs
  storage:
    type: persistent-claim
    class: hostpath
    size: 20Gi
    deleteClaim: false
