apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-runtime-logs-0
  namespace: kafka
  labels:
    app.kubernetes.io/name: kafka-runtime-logs
    strimzi.io/cluster: kafka
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-runtime-logs-1
  namespace: kafka
  labels:
    app.kubernetes.io/name: kafka-runtime-logs
    strimzi.io/cluster: kafka
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-runtime-logs-2
  namespace: kafka
  labels:
    app.kubernetes.io/name: kafka-runtime-logs
    strimzi.io/cluster: kafka
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 2Gi
